targets:
  $default:
    builders:
      functional_widget:
        options:
          # Default values:
          debugFillProperties: false
          widgetType: hook # or 'stateless'
          equality: none # or 'identical'/'equal'
